// <auto-generated />
using System;
using Kolokwium.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kolokwium.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220630170035_v2")]
    partial class v2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KolokwiumPoprawa.Models.File", b =>
                {
                    b.Property<int>("FileID")
                        .HasColumnType("int");

                    b.Property<int>("TeamID")
                        .HasColumnType("int");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FileSize")
                        .HasColumnType("int");

                    b.HasKey("FileID", "TeamID");

                    b.HasIndex("TeamID");

                    b.ToTable("Files");

                    b.HasData(
                        new
                        {
                            FileID = 1,
                            TeamID = 1,
                            FileExtension = "ext1",
                            FileName = "1",
                            FileSize = 340
                        },
                        new
                        {
                            FileID = 2,
                            TeamID = 3,
                            FileExtension = "ext2",
                            FileName = "2",
                            FileSize = 320
                        },
                        new
                        {
                            FileID = 3,
                            TeamID = 4,
                            FileExtension = "ext1",
                            FileName = "3",
                            FileSize = 402
                        },
                        new
                        {
                            FileID = 4,
                            TeamID = 1,
                            FileExtension = "ext2",
                            FileName = "4",
                            FileSize = 502
                        },
                        new
                        {
                            FileID = 5,
                            TeamID = 2,
                            FileExtension = "ext3",
                            FileName = "5",
                            FileSize = 224
                        },
                        new
                        {
                            FileID = 6,
                            TeamID = 4,
                            FileExtension = "ext4",
                            FileName = "6",
                            FileSize = 19
                        },
                        new
                        {
                            FileID = 7,
                            TeamID = 2,
                            FileExtension = "ext1",
                            FileName = "7",
                            FileSize = 84
                        },
                        new
                        {
                            FileID = 8,
                            TeamID = 1,
                            FileExtension = "ext2",
                            FileName = "8",
                            FileSize = 921
                        });
                });

            modelBuilder.Entity("KolokwiumPoprawa.Models.Member", b =>
                {
                    b.Property<int>("MemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MemberName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MemberNickName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MemberSurname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OrganizationID")
                        .HasColumnType("int");

                    b.HasKey("MemberID");

                    b.HasIndex("OrganizationID");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            MemberID = 1,
                            MemberName = "1",
                            MemberSurname = "1",
                            OrganizationID = 1
                        },
                        new
                        {
                            MemberID = 2,
                            MemberName = "2",
                            MemberSurname = "2",
                            OrganizationID = 2
                        },
                        new
                        {
                            MemberID = 3,
                            MemberName = "3",
                            MemberSurname = "3",
                            OrganizationID = 1
                        },
                        new
                        {
                            MemberID = 4,
                            MemberName = "4",
                            MemberSurname = "4",
                            OrganizationID = 2
                        });
                });

            modelBuilder.Entity("KolokwiumPoprawa.Models.Membership", b =>
                {
                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<int>("TeamID")
                        .HasColumnType("int");

                    b.Property<DateTime>("MembershipDate")
                        .HasColumnType("datetime2");

                    b.HasKey("MemberID", "TeamID");

                    b.HasIndex("TeamID");

                    b.ToTable("Memberships");

                    b.HasData(
                        new
                        {
                            MemberID = 3,
                            TeamID = 3,
                            MembershipDate = new DateTime(2019, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MemberID = 2,
                            TeamID = 4,
                            MembershipDate = new DateTime(2017, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MemberID = 3,
                            TeamID = 2,
                            MembershipDate = new DateTime(2018, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MemberID = 1,
                            TeamID = 1,
                            MembershipDate = new DateTime(2015, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MemberID = 4,
                            TeamID = 3,
                            MembershipDate = new DateTime(2019, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MemberID = 2,
                            TeamID = 1,
                            MembershipDate = new DateTime(2022, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("KolokwiumPoprawa.Models.Organization", b =>
                {
                    b.Property<int>("OrganizationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OrganizationDomain")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("OrganizationID");

                    b.ToTable("Organizations");

                    b.HasData(
                        new
                        {
                            OrganizationID = 1,
                            OrganizationDomain = "1",
                            OrganizationName = "1"
                        },
                        new
                        {
                            OrganizationID = 2,
                            OrganizationDomain = "2",
                            OrganizationName = "2"
                        });
                });

            modelBuilder.Entity("KolokwiumPoprawa.Models.Team", b =>
                {
                    b.Property<int>("TeamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OrganizationID")
                        .HasColumnType("int");

                    b.Property<string>("TeamDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TeamID");

                    b.HasIndex("OrganizationID");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            TeamID = 1,
                            OrganizationID = 1,
                            TeamDescription = "1",
                            TeamName = "1"
                        },
                        new
                        {
                            TeamID = 2,
                            OrganizationID = 2,
                            TeamDescription = "2",
                            TeamName = "2"
                        },
                        new
                        {
                            TeamID = 3,
                            OrganizationID = 1,
                            TeamDescription = "3",
                            TeamName = "3"
                        },
                        new
                        {
                            TeamID = 4,
                            OrganizationID = 2,
                            TeamDescription = "4",
                            TeamName = "4"
                        });
                });

            modelBuilder.Entity("KolokwiumPoprawa.Models.File", b =>
                {
                    b.HasOne("KolokwiumPoprawa.Models.Team", "Team")
                        .WithMany("Files")
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("KolokwiumPoprawa.Models.Member", b =>
                {
                    b.HasOne("KolokwiumPoprawa.Models.Organization", "Organization")
                        .WithMany("Members")
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("KolokwiumPoprawa.Models.Membership", b =>
                {
                    b.HasOne("KolokwiumPoprawa.Models.Member", "Member")
                        .WithMany("Memberships")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("KolokwiumPoprawa.Models.Team", "Team")
                        .WithMany("Memberships")
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("KolokwiumPoprawa.Models.Team", b =>
                {
                    b.HasOne("KolokwiumPoprawa.Models.Organization", "Organization")
                        .WithMany("Teams")
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("KolokwiumPoprawa.Models.Member", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("KolokwiumPoprawa.Models.Organization", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("KolokwiumPoprawa.Models.Team", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
